version: '3'
services:
  maxilog-nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  maxilog-postgresql:
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresDB:/var/lib/postgresql/data
      - ./data/postgres-entrypoint:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: maxilog-default
      POSTGRES_USER: maxilog-default-user
      POSTGRES_PASSWORD: maxilog-default-password

  maxilog-keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - '8180:8080'
    environment:
      DB_VENDOR: postgres
      DB_ADDR: maxilog-postgresql
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: maxilog-keycloak-user
      DB_PASSWORD: maxilog-keycloak-password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command: >
      start-dev 
      --import-realm 
      -Dkeycloak.migration.provider=singleFile
      -Dkeycloak.migration.file=/opt/keycloak/data/import/realm-init.json
      -Dkeycloak.migration.strategy=IGNORE_EXISTING
    volumes:
      - ./data/realm:/opt/keycloak/data/import
